give azure-cli a run depend on devel/py-futures
avoids the following error with 'az storage blob download'

No module named concurrent.futures
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/azure/cli/main.py", line 37, in main
    cmd_result = APPLICATION.execute(args)
  File "/usr/local/lib/python2.7/site-packages/azure/cli/core/application.py", line 157, in execute
    result = expanded_arg.func(params)
  File "/usr/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 343, in _execute
_command
    raise ex
ImportError: No module named concurrent.futures