attempt to use combined distfiles
This may not be possible for azure-sdk as everything is not released as
at the same time and individual releases don't get a git tag.

azure-mgmt-resource 0.31.0 can't be used as it removes a file
used by the latest azure-cli-resource so 0.30.2 is needed.

A snapshot of azure-sdk is used as the last tag does not include
azure-mgmt-containerregistry which is required by azure-cli-acr.

For some reason the network command module doesn't load with these changes:

ERROR: Error loading command module 'network'
DEBUG: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 214, in get_command_table
    import_module('azure.cli.command_modules.' + mod).load_commands()
  File "/usr/local/lib/python2.7/site-packages/azure/cli/command_modules/network/__init__.py", line 12, in load_commands
    import azure.cli.command_modules.network.commands #pylint: disable=redefined-outer-name
  File "/usr/local/lib/python2.7/site-packages/azure/cli/command_modules/network/commands.py", line 402, in <module>
    cli_command(__name__, 'network dns record-set list', 'azure.mgmt.dns.operations.record_sets_operations#RecordSetsOperations.list_all_in_resource_group', cf_dns_mgmt_record_sets)
  File "/usr/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 247, in cli_command
    client_factory, no_wait_param)
  File "/usr/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 311, in create_command
    arguments_loader=arguments_loader, description_loader=description_loader)
  File "/usr/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 154, in __init__
    if description_loader and CliCommand._should_load_description() \
  File "/usr/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 309, in <lambda>
    description_loader = lambda: extract_full_summary_from_signature(get_op_handler(operation))
  File "/usr/local/lib/python2.7/site-packages/azure/cli/core/commands/__init__.py", line 258, in get_op_handler
    raise ValueError("The operation '{}' is invalid.".format(operation))
ValueError: The operation 'azure.mgmt.dns.operations.record_sets_operations#RecordSetsOperations.list_all_in_resource_group' is invalid.